In [254]:
import pandas as pd
import numpy as np

In [255]:
df=pd.read_csv("./data/HouseRentPrediction.csv")

In [256]:
df.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [257]:
#df=df.drop(labels=["Floor"],axis=1)
#df=df.drop(labels=["Posted On"],axis=1)
#df=df.drop(labels=["Area Locality"],axis=1)

In [258]:
df=df.drop(labels=["Posted On"],axis=1)

In [259]:
df.isnull().sum()

BHK                  0
Rent                 0
Size                 0
Floor                0
Area Type            0
Area Locality        0
City                 0
Furnishing Status    0
Tenant Preferred     0
Bathroom             0
Point of Contact     0
dtype: int64

In [260]:
df.head()

,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [261]:
df.columns

Index(['BHK', 'Rent', 'Size', 'Floor', 'Area Type', 'Area Locality', 'City',
       'Furnishing Status', 'Tenant Preferred', 'Bathroom',
       'Point of Contact'],
      dtype='object')

In [262]:
x=df.drop(labels=["Rent"],axis=1)

In [263]:
y=df[["Rent"]]

In [264]:
x

,BHK,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...
4741,2,1000,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,3,2000,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,3,1750,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,3,1500,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2,1000,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [265]:
y

       Rent
0     10000
1     20000
2     17000
3     10000
4      7500
...     ...
4741  15000
4742  29000
4743  35000
4744  45000
4745  15000

[4746 rows x 1 columns]

In [266]:
categorical_cols=x.select_dtypes(include="object").columns

In [267]:
numerical_cols=x.select_dtypes(exclude="object").columns

In [268]:
x.select_dtypes(include="object")

,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Point of Contact
0,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,Contact Owner
1,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,Contact Owner
2,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,Contact Owner
3,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,Contact Owner
4,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,Contact Owner
...,...,...,...,...,...,...,...
4741,3 out of 5,Carpet Area,Bandam Kommu,Hyderabad,Semi-Furnished,Bachelors/Family,Contact Owner
4742,1 out of 4,Super Area,"Manikonda, Hyderabad",Hyderabad,Semi-Furnished,Bachelors/Family,Contact Owner
4743,3 out of 5,Carpet Area,"Himayath Nagar, NH 7",Hyderabad,Semi-Furnished,Bachelors/Family,Contact Agent
4744,23 out of 34,Carpet Area,Gachibowli,Hyderabad,Semi-Furnished,Family,Contact Agent
4745,4 out of 5,Carpet Area,Suchitra Circle,Hyderabad,Unfurnished,Bachelors,Contact Owner

In [269]:
y.select_dtypes(exclude="object").columns

Index(['Rent'], dtype='object')

In [270]:
categorical_cols

Index(['Floor', 'Area Type', 'Area Locality', 'City', 'Furnishing Status',
       'Tenant Preferred', 'Point of Contact'],
      dtype='object')

In [271]:
numerical_cols

Index(['BHK', 'Size', 'Bathroom'], dtype='object')

In [272]:
#customized ranking for each ordinal variable
Area_Type_categories=["Super Area", "Carpet Area", "Built Area"]
City_categories=['Kolkata', 'Mumbai', 'Bangalore', 'Delhi', 'Chennai', 'Hyderabad']
Furnishing_Status_categories=['Unfurnished', 'Semi-Furnished', 'Furnished']
Tenant_Preferred_categories=['Bachelors/Family', 'Bachelors', 'Family']
Point_of_Contact_categories=['Contact Owner', 'Contact Agent', 'Contact Builder']

In [273]:
from sklearn.impute import SimpleImputer ##for handling missing values
from sklearn.preprocessing import StandardScaler ## Handling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder ##Ordinal Encoder
##pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [274]:
num_pipeline=Pipeline(
    
    steps=[
        
        ("imputer",SimpleImputer()),
        ("scaler",StandardScaler())
        
    ]
    
)

In [275]:
cat_pipeline=Pipeline(
    
    steps=[
        
        ('imputer',SimpleImputer(strategy="most_frequent")),
        ('ordinalencoder',OrdinalEncoder(categories=[Area_Type_categories,City_categories,Furnishing_Status_categories,Tenant_Preferred_categories,Point_of_Contact_categories]))
        
    ]
    
)

In [276]:
preprocessor=ColumnTransformer(
     [
        
        ('num_pipeline',num_pipeline,numerical_cols),
        ('cat_pipeline',cat_pipeline,categorical_cols)
     ]
)

In [277]:
## train test split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=30)

In [278]:
preprocessor.fit_transform(x_train)

ValueError: Shape mismatch: if categories is an array, it has to be of shape (n_features,).

In [ ]:
preprocessor.get_feature_names_out()

array(['num_pipeline__BHK', 'num_pipeline__Size',
       'num_pipeline__Bathroom', 'cat_pipeline__Area Type',
       'cat_pipeline__City', 'cat_pipeline__Furnishing Status',
       'cat_pipeline__Tenant Preferred', 'cat_pipeline__Point of Contact'],
      dtype=object)

In [ ]:
x_train=pd.DataFrame(preprocessor.fit_transform(x_train),columns=preprocessor.get_feature_names_out())
x_test=pd.DataFrame(preprocessor.transform(x_test),columns=preprocessor.get_feature_names_out())

In [ ]:
x_train

,num_pipeline__BHK,num_pipeline__Size,num_pipeline__Bathroom,cat_pipeline__Area Type,cat_pipeline__City,cat_pipeline__Furnishing Status,cat_pipeline__Tenant Preferred,cat_pipeline__Point of Contact
0,-0.110397,-1.445857,0.030115,0.0,3.0,1.0,0.0,0.0
1,-0.110397,0.523590,0.030115,0.0,3.0,0.0,1.0,1.0
2,-1.315624,-0.757351,-1.110097,0.0,0.0,1.0,0.0,0.0
3,2.300056,0.443531,2.310539,1.0,1.0,2.0,2.0,1.0
4,1.094829,-1.197674,1.170327,1.0,5.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...
3554,-1.315624,-0.837410,0.030115,1.0,1.0,2.0,2.0,1.0
3555,-1.315624,-0.725327,0.030115,0.0,1.0,1.0,0.0,0.0
3556,-0.110397,-0.276998,-1.110097,0.0,0.0,0.0,0.0,0.0
3557,-0.110397,-0.068845,0.030115,0.0,5.0,1.0,0.0,0.0
3558,-0.110397,-0.276998,0.030115,0.0,5.0,1.0,0.0,0.0

In [ ]:
x_test

,num_pipeline__BHK,num_pipeline__Size,num_pipeline__Bathroom,cat_pipeline__Area Type,cat_pipeline__City,cat_pipeline__Furnishing Status,cat_pipeline__Tenant Preferred,cat_pipeline__Point of Contact
0,1.094829,0.123296,1.170327,1.0,1.0,2.0,0.0,1.0
1,-1.315624,-0.906260,0.030115,0.0,1.0,0.0,0.0,0.0
2,-0.110397,-0.437116,-1.110097,1.0,2.0,1.0,0.0,0.0
3,-1.315624,-0.997527,-1.110097,0.0,2.0,0.0,0.0,0.0
4,-0.110397,0.363472,0.030115,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...
1182,-0.110397,-0.405092,0.030115,1.0,0.0,1.0,0.0,0.0
1183,1.094829,1.324178,1.170327,1.0,2.0,1.0,0.0,0.0
1184,-0.110397,-0.357057,0.030115,1.0,1.0,2.0,1.0,1.0
1185,-0.110397,-0.357057,0.030115,1.0,0.0,0.0,0.0,1.0
1186,-1.315624,-0.276998,-1.110097,1.0,2.0,0.0,0.0,1.0

In [ ]:
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression,Ridge,Lasso,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [ ]:
import numpy as np
def evaluate_model(true,predicted):
    mae = mean_absolute_error(true,predicted)
    mse = mean_squared_error(true,predicted)
    rmse = np.sqrt(mean_squared_error(true,predicted))
    r2_square = r2_score(true,predicted)
    return mae, rmse, r2_square

In [ ]:
models = {
    'Linear Regression': LinearRegression(),
    'Lasso': Lasso(),
    'Ridge': Ridge(),
    'Elasticnet': ElasticNet(),  # Added comma here
    'K-Neighbors Regression': KNeighborsRegressor(),
    'Decision Tree': DecisionTreeRegressor(),
    'XGBRegressor': XGBRegressor(),
    'CatBoosting Regressor': CatBoostRegressor(verbose=False),
    'AdaBoost Regressor': AdaBoostRegressor()
}

In [ ]:
list(models)

['Linear Regression',
 'Lasso',
 'Ridge',
 'Elasticnet',
 'K-Neighbors Regression',
 'Decision Tree',
 'XGBRegressor',
 'CatBoosting Regressor',
 'AdaBoost Regressor']

In [ ]:
for i in range(len(list(models))):
    model=list(models.values())[i]
    print(model)

LinearRegression()
Lasso()
Ridge()
ElasticNet()
KNeighborsRegressor()
DecisionTreeRegressor()
XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...)
<catboost.core.CatBoostRegressor object at 0x000001CEA33BFE80>
AdaBoostRegressor()

In [ ]:
trained_model_list=[]
model_list=[]
r2_list=[]

In [ ]:
list(models)

['Linear Regression',
 'Lasso',
 'Ridge',
 'Elasticnet',
 'K-Neighbors Regression',
 'Decision Tree',
 'XGBRegressor',
 'CatBoosting Regressor',
 'AdaBoost Regressor']

In [ ]:
models.values()

dict_values([LinearRegression(), Lasso(), Ridge(), ElasticNet(), KNeighborsRegressor(), DecisionTreeRegressor(), XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=None, max_bin=None,
             max_cat_threshold=None, max_cat_to_onehot=None,
             max_delta_step=None, max_depth=None, max_leaves=None,
             min_child_weight=None, missing=nan, monotone_constraints=None,
             multi_strategy=None, n_estimators=None, n_jobs=None,
             num_parallel_tree=None, random_state=None, ...), <catboost.core.CatBoostRegressor object at 0x000001CEA33BFE80>, AdaBoostRegressor()])